version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --passWithNoTests
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Deploy app to server
          command: curl 'https://get-your-book-server.onrender.com'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
